version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    networks:
      - inner_network
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    networks:
      - inner_network

networks:
  inner_network: