version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
    ports:
      - '80:3000'
    depends_on:
      - backend